{% set name = "vbmicrolensing" %}
{% set version = "5.3.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 83a3b8cb877d96aaa8bb51230435bf32b664c2e12cd27f5e82804a8c72d58dc8

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
    - ninja
    - pybind11
  host:
    - python
    - pip
    - scikit-build-core >=0.10
    - pybind11
    - numpy
    - setuptools
  run:
    - python
    - numpy

test:
  imports:
    - VBMicrolensing

about:
  home: https://github.com/valboz/VBMicrolensing
  summary: "Efficient computation in gravitational microlensing events using advanced contour integration."
  description: |
    VBMicrolensing is a tool for efficient computation in gravitational microlensing events using the advanced contour integration method, supporting single, binary and multiple lenses.
  license: LGPL-3.0
  license_family: LGPL
  license_file: LICENSE
  doc_url: https://github.com/valboz/VBMicrolensing
  dev_url: https://github.com/valboz/VBMicrolensing

extra:
  recipe-maintainers:
    - valboz
    - VitoSaggese
    - AmberLee2427
